import type { CurrencyMeta } from './types'

/** Tuple form keeps the table compact: [code, name, flag, symbol?]. */
type FiatRow = readonly [code: string, name: string, flag: string, symbol?: string]

const FIAT_ROWS: readonly FiatRow[] = [
  ['aed', 'United Arab Emirates Dirham', 'ae', 'د.إ'],
  ['afn', 'Afghan Afghani', 'af', '؋'],
  ['all', 'Albanian Lek', 'al', 'L'],
  ['amd', 'Armenian Dram', 'am', '֏'],
  ['ang', 'Netherlands Antillean Guilder', 'cw', 'ƒ'],
  ['aoa', 'Angolan Kwanza', 'ao', 'Kz'],
  ['ars', 'Argentine Peso', 'ar', '$'],
  ['aud', 'Australian Dollar', 'au', 'A$'],
  ['awg', 'Aruban Florin', 'aw', 'ƒ'],
  ['azn', 'Azerbaijani Manat', 'az', '₼'],
  ['bam', 'Bosnia-Herzegovina Convertible Mark', 'ba', 'KM'],
  ['bbd', 'Barbadian Dollar', 'bb', 'Bds$'],
  ['bdt', 'Bangladeshi Taka', 'bd', '৳'],
  ['bgn', 'Bulgarian Lev', 'bg', 'лв'],
  ['bhd', 'Bahraini Dinar', 'bh', '.د.ب'],
  ['bif', 'Burundian Franc', 'bi', 'FBu'],
  ['bmd', 'Bermudian Dollar', 'bm', 'BD$'],
  ['bnd', 'Brunei Dollar', 'bn', 'B$'],
  ['bob', 'Bolivian Boliviano', 'bo', 'Bs.'],
  ['brl', 'Brazilian Real', 'br', 'R$'],
  ['bsd', 'Bahamian Dollar', 'bs', 'B$'],
  ['btn', 'Bhutanese Ngultrum', 'bt', 'Nu.'],
  ['bwp', 'Botswana Pula', 'bw', 'P'],
  ['byn', 'Belarusian Ruble', 'by', 'Br'],
  ['bzd', 'Belize Dollar', 'bz', 'BZ$'],
  ['cad', 'Canadian Dollar', 'ca', 'C$'],
  ['cdf', 'Congolese Franc', 'cd', 'FC'],
  ['chf', 'Swiss Franc', 'ch', 'CHF'],
  ['clp', 'Chilean Peso', 'cl', '$'],
  ['cny', 'Chinese Yuan', 'cn', '¥'],
  ['cop', 'Colombian Peso', 'co', '$'],
  ['crc', 'Costa Rican Colón', 'cr', '₡'],
  ['cup', 'Cuban Peso', 'cu', '$'],
  ['cve', 'Cape Verdean Escudo', 'cv', '$'],
  ['czk', 'Czech Koruna', 'cz', 'Kč'],
  ['djf', 'Djiboutian Franc', 'dj', 'Fdj'],
  ['dkk', 'Danish Krone', 'dk', 'kr'],
  ['dop', 'Dominican Peso', 'do', 'RD$'],
  ['dzd', 'Algerian Dinar', 'dz', 'د.ج'],
  ['egp', 'Egyptian Pound', 'eg', 'E£'],
  ['ern', 'Eritrean Nakfa', 'er', 'Nfk'],
  ['etb', 'Ethiopian Birr', 'et', 'Br'],
  ['eur', 'Euro', 'eu', '€'],
  ['fjd', 'Fijian Dollar', 'fj', 'FJ$'],
  ['fkp', 'Falkland Islands Pound', 'fk', '£'],
  ['gbp', 'British Pound Sterling', 'gb', '£'],
  ['gel', 'Georgian Lari', 'ge', '₾'],
  ['ghs', 'Ghanaian Cedi', 'gh', '₵'],
  ['gip', 'Gibraltar Pound', 'gi', '£'],
  ['gmd', 'Gambian Dalasi', 'gm', 'D'],
  ['gnf', 'Guinean Franc', 'gn', 'FG'],
  ['gtq', 'Guatemalan Quetzal', 'gt', 'Q'],
  ['gyd', 'Guyanese Dollar', 'gy', 'G$'],
  ['hkd', 'Hong Kong Dollar', 'hk', 'HK$'],
  ['hnl', 'Honduran Lempira', 'hn', 'L'],
  ['htg', 'Haitian Gourde', 'ht', 'G'],
  ['huf', 'Hungarian Forint', 'hu', 'Ft'],
  ['idr', 'Indonesian Rupiah', 'id', 'Rp'],
  ['ils', 'Israeli New Shekel', 'il', '₪'],
  ['inr', 'Indian Rupee', 'in', '₹'],
  ['iqd', 'Iraqi Dinar', 'iq', 'ع.د'],
  ['irr', 'Iranian Rial', 'ir', '﷼'],
  ['isk', 'Icelandic Króna', 'is', 'kr'],
  ['jmd', 'Jamaican Dollar', 'jm', 'J$'],
  ['jod', 'Jordanian Dinar', 'jo', 'د.ا'],
  ['jpy', 'Japanese Yen', 'jp', '¥'],
  ['kes', 'Kenyan Shilling', 'ke', 'KSh'],
  ['kgs', 'Kyrgyzstani Som', 'kg', 'с'],
  ['khr', 'Cambodian Riel', 'kh', '៛'],
  ['kmf', 'Comorian Franc', 'km', 'CF'],
  ['kpw', 'North Korean Won', 'kp', '₩'],
  ['krw', 'South Korean Won', 'kr', '₩'],
  ['kwd', 'Kuwaiti Dinar', 'kw', 'د.ك'],
  ['kyd', 'Cayman Islands Dollar', 'ky', 'CI$'],
  ['kzt', 'Kazakhstani Tenge', 'kz', '₸'],
  ['lak', 'Lao Kip', 'la', '₭'],
  ['lbp', 'Lebanese Pound', 'lb', 'ل.ل'],
  ['lkr', 'Sri Lankan Rupee', 'lk', 'Rs'],
  ['lrd', 'Liberian Dollar', 'lr', 'L$'],
  ['lsl', 'Lesotho Loti', 'ls', 'L'],
  ['lyd', 'Libyan Dinar', 'ly', 'ل.د'],
  ['mad', 'Moroccan Dirham', 'ma', 'د.م.'],
  ['mdl', 'Moldovan Leu', 'md', 'L'],
  ['mga', 'Malagasy Ariary', 'mg', 'Ar'],
  ['mkd', 'Macedonian Denar', 'mk', 'ден'],
  ['mmk', 'Myanmar Kyat', 'mm', 'K'],
  ['mnt', 'Mongolian Tögrög', 'mn', '₮'],
  ['mop', 'Macanese Pataca', 'mo', 'MOP$'],
  ['mru', 'Mauritanian Ouguiya', 'mr', 'UM'],
  ['mur', 'Mauritian Rupee', 'mu', '₨'],
  ['mvr', 'Maldivian Rufiyaa', 'mv', 'Rf'],
  ['mwk', 'Malawian Kwacha', 'mw', 'MK'],
  ['mxn', 'Mexican Peso', 'mx', '$'],
  ['myr', 'Malaysian Ringgit', 'my', 'RM'],
  ['mzn', 'Mozambican Metical', 'mz', 'MT'],
  ['nad', 'Namibian Dollar', 'na', 'N$'],
  ['ngn', 'Nigerian Naira', 'ng', '₦'],
  ['nio', 'Nicaraguan Córdoba', 'ni', 'C$'],
  ['nok', 'Norwegian Krone', 'no', 'kr'],
  ['npr', 'Nepalese Rupee', 'np', '₨'],
  ['nzd', 'New Zealand Dollar', 'nz', 'NZ$'],
  ['omr', 'Omani Rial', 'om', 'ر.ع.'],
  ['pab', 'Panamanian Balboa', 'pa', 'B/.'],
  ['pen', 'Peruvian Sol', 'pe', 'S/'],
  ['pgk', 'Papua New Guinean Kina', 'pg', 'K'],
  ['php', 'Philippine Peso', 'ph', '₱'],
  ['pkr', 'Pakistani Rupee', 'pk', '₨'],
  ['pln', 'Polish Złoty', 'pl', 'zł'],
  ['pyg', 'Paraguayan Guaraní', 'py', '₲'],
  ['qar', 'Qatari Riyal', 'qa', 'ر.ق'],
  ['ron', 'Romanian Leu', 'ro', 'lei'],
  ['rsd', 'Serbian Dinar', 'rs', 'дин.'],
  ['rub', 'Russian Ruble', 'ru', '₽'],
  ['rwf', 'Rwandan Franc', 'rw', 'FRw'],
  ['sar', 'Saudi Riyal', 'sa', 'ر.س'],
  ['sbd', 'Solomon Islands Dollar', 'sb', 'SI$'],
  ['scr', 'Seychellois Rupee', 'sc', '₨'],
  ['sdg', 'Sudanese Pound', 'sd', 'ج.س.'],
  ['sek', 'Swedish Krona', 'se', 'kr'],
  ['sgd', 'Singapore Dollar', 'sg', 'S$'],
  ['shp', 'Saint Helena Pound', 'sh', '£'],
  ['sle', 'Sierra Leonean Leone', 'sl', 'Le'],
  ['sos', 'Somali Shilling', 'so', 'Sh'],
  ['srd', 'Surinamese Dollar', 'sr', '$'],
  ['ssp', 'South Sudanese Pound', 'ss', '£'],
  ['stn', 'São Tomé and Príncipe Dobra', 'st', 'Db'],
  ['syp', 'Syrian Pound', 'sy', '£S'],
  ['szl', 'Swazi Lilangeni', 'sz', 'E'],
  ['thb', 'Thai Baht', 'th', '฿'],
  ['tjs', 'Tajikistani Somoni', 'tj', 'SM'],
  ['tmt', 'Turkmenistani Manat', 'tm', 'm'],
  ['tnd', 'Tunisian Dinar', 'tn', 'د.ت'],
  ['top', 'Tongan Paʻanga', 'to', 'T$'],
  ['try', 'Turkish Lira', 'tr', '₺'],
  ['ttd', 'Trinidad and Tobago Dollar', 'tt', 'TT$'],
  ['twd', 'New Taiwan Dollar', 'tw', 'NT$'],
  ['tzs', 'Tanzanian Shilling', 'tz', 'TSh'],
  ['uah', 'Ukrainian Hryvnia', 'ua', '₴'],
  ['ugx', 'Ugandan Shilling', 'ug', 'USh'],
  ['usd', 'United States Dollar', 'us', '$'],
  ['uyu', 'Uruguayan Peso', 'uy', '$U'],
  ['uzs', 'Uzbekistani Som', 'uz', 'soʻm'],
  ['ves', 'Venezuelan Bolívar', 've', 'Bs.'],
  ['vnd', 'Vietnamese Dong', 'vn', '₫'],
  ['vuv', 'Vanuatu Vatu', 'vu', 'VT'],
  ['wst', 'Samoan Tālā', 'ws', 'WS$'],
  ['xaf', 'Central African CFA Franc', 'cm', 'FCFA'],
  ['xcd', 'East Caribbean Dollar', 'ag', 'EC$'],
  ['xof', 'West African CFA Franc', 'sn', 'CFA'],
  ['xpf', 'CFP Franc', 'pf', '₣'],
  ['yer', 'Yemeni Rial', 'ye', '﷼'],
  ['zar', 'South African Rand', 'za', 'R'],
  ['zmw', 'Zambian Kwacha', 'zm', 'ZK'],
  ['zwg', 'Zimbabwe Gold', 'zw', 'ZiG'],
]

export const FIAT_CURRENCIES: readonly CurrencyMeta[] = FIAT_ROWS.map(
  ([code, name, flag, symbol]) => ({ code, name, type: 'fiat', flag, symbol }),
)
